//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_firtst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Eticaret_vtEntities : DbContext
    {
        public Eticaret_vtEntities()
            : base("name=Eticaret_vtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<altkategoriler> altkategoriler { get; set; }
        public virtual DbSet<favoriler> favoriler { get; set; }
        public virtual DbSet<kategoriler> kategoriler { get; set; }
        public virtual DbSet<meslek> meslek { get; set; }
        public virtual DbSet<sehirler> sehirler { get; set; }
        public virtual DbSet<siparisler> siparisler { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<uyeler> uyeler { get; set; }
        public virtual DbSet<toplam_kazan> toplam_kazan { get; set; }
    }
}
