//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_first.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hasta_yatis
    {
        public int Id { get; set; }
        public System.DateTime yat_tarihi { get; set; }
        public System.DateTime cik_tarihi { get; set; }
        public byte oda_no { get; set; }
        public int hasta_no { get; set; }
        public int Doktor_no { get; set; }
        public int Dept_no { get; set; }
    
        public virtual Hastalar Hastalar { get; set; }
        public virtual Doktorlar Doktorlar { get; set; }
        public virtual Departmanlar Departmanlar { get; set; }
    }
}
