//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_first.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hastane_modelContainer : DbContext
    {
        public Hastane_modelContainer()
            : base("name=Hastane_modelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hastalar> Hastalar { get; set; }
        public virtual DbSet<Hasta_yatis> Hasta_yatis { get; set; }
        public virtual DbSet<Departmanlar> Departman { get; set; }
        public virtual DbSet<Doktorlar> Doktorlar { get; set; }
    }
}
